### ISSUE TITLE
trouble with multifasta.fna

### ISSUE THREAD

**Issue by ykm7788** [dcouvin/CRISPRCasFinder#17]
Hi, thank you for developing such a useful tool !

I successfully installed this software with a solid result of functional test.

But when I try to run a test for a multifasta file like this :

>\>A1_scaffold1
TGTTTGTTTGTTAAAGAACTGCGCGATCAACTTTGTTCATCGCGTCGCTGCGT...
>\>A1_scaffold10
CGCACTCCGTCCGTATCGCCTGAATTCAAGATCATAGGTGGACCTGTGTCTTC...
>\>A1_scaffold100
GAGGCGAGGGTGGGGGACCTGCGCGTGCAGGTGCCGGGCCTGTTCGGGCAACT...
>\>A1_scaffold1008
CGGCCGACTTCTCGGAGACGATGGTCAGGCCGAGCCGCTTCTTGAAGGTGCCG...

It seems only readed in the first A1_scaffold1 sequence, as all temporary files created were about A1_scaffold1 only.

My command is like this:
`perl CRISPRCasFinder.pl -i A1.seq.fna -out A1 -cas -def  -rpts -rcfowce -gff A1.crispr.gff -faa A1.crispr.faa -meta -ccvr`

With this output :

>################################################################
>\# --> Welcome to /home/umaru/software/CRISPRCasFinder/CRISPRCasFinder/CRISPRCasFinder.pl (version 4.2.17) 
>################################################################

>vmatch2 is...............OK 
>mkvtree2 is...............OK 
>vsubseqselect2 is...............OK 
>fuzznuc (from emboss) is...............OK 
>needle (from emboss) is...............OK 

>[16:31:19] ---> Results will be stored in A1

>Sequence number 1..  ( Input file: A1_scaffold1.fna, Sequence ID: A1_scaffold1, Sequence name = Unknown )
>The shared object file (./sel392v2.so) must be available in your current directory. Otherwise, you must use option -soFile (or -so)! 

So, anything wrong ?

**Comment by dcouvin** [comment]
Hi @ykm7788 ,
Thank you for your message.
Indeed, some data are missing in your command line. For example, a letter is expected after the option '-def' in order to define the corresponding Cas system ('General' or 'G' for general classification, or other parameters such as 'Typing' or 'T', and 'SubTyping' or 'S'). A path to repeat file is also expected after '-rpts' option (supplementary_files/Repeat_List.csv). Furthermore, you will need the '-so' option to specify the path to 'sel392v2.so' file generated in your CRISPRCasFinder folder after installation. Please read the provided user manual for further details (https://github.com/dcouvin/CRISPRCasFinder/blob/master/CRISPRCasFinder_Viewer_manual.pdf).
Best regards,
David
