### ISSUE TITLE
Is there a way to simply get a list of spacers?

### ISSUE THREAD

**Issue by chahatupreti** [dcouvin/CRISPRCasFinder#19]
Hello,

I have downloaded CCfinder since I want to run it on hundreds of draft genomes. I am mainly interested in finding the list of spacers in each of them. After running CCfinder and seeing the results, I couldn't find a simple way to get to such a list. In the online version, there is a simple button to download spacers. Is it possible to achieve that in the downloadable version of the software?

I cant find the spacers in either the `Crisprs_REPORT.tsv` or the `CRISPR-Cas_summary.tsv`.

For reference, here is the command I am running (on Mac) - 

`./CRISPRCasFinder.pl  -i /path/to/my/input.fa -out /path/to/my/output`

**Comment by chahatupreti** [comment]
Anybody have any ideas?

**Comment by dcouvin** [comment]
Dear Chahat,
Thank you for your message. Sorry for the delayed response due to other
ongoing works.
You can use the '-keep' option in order to download the spacers
cooresponding to each analyzed sequence. You will find these results in the
'CRISPRFinderProperties' generated folder. You can also download the
repeats. See the user manual for other options. Do not hesitate if you have
further questions.
Best regards,
David

Le jeu. 16 juil. 2020 11:55, Chahat Upreti <notifications@github.com> a
écrit :

**Comment by chahatupreti** [comment]
Thank you so much David for the response. I did try to run with the -keep option, but there was no 'CRISPRFinderProperties' folder in the output. 

My code was - `/.../CRISPRCasFinder.pl  -i /.../NC_017316.1.fa -out /.../NC_017316.1 –keep`

And the folders in the output are attached as a screenshot. What do you think could be happening?

Thank you!
![Screen Shot 2020-07-21 at 8 47 18 PM](https://user-images.githubusercontent.com/9638057/88124869-b83f2b00-cb93-11ea-8ded-509c81be2b23.png)

**Comment by chahatupreti** [comment]
Actually I then tried to put the -keep option twice as in `-keep -keep` and that did the trick!

Thank you!

**Comment by dcouvin** [comment]
Great! You are welcome!

>
