### ISSUE TITLE
Discrepancy between Direct Repeat sequences

### ISSUE THREAD

**Issue by chahatupreti** [dcouvin/CRISPRCasFinder#22]
Hello!

I ran CrisprCasFinder on a bacterial genome. A picture of the output folder is attached. 
![Screen Shot 2020-08-17 at 8 57 23 PM](https://user-images.githubusercontent.com/9638057/90461597-54dde580-e0cc-11ea-88c0-8c4db6367d94.png)

The content of the highlighted files however is not the same. Aren't the files DRs_2 and DRs_2_fasta supposed to be the same thing? Here is the content of those two files - 

DRs_2 
![Screen Shot 2020-08-17 at 9 00 00 PM](https://user-images.githubusercontent.com/9638057/90461723-a5edd980-e0cc-11ea-8a1c-cc107e4881ae.png)

and DRs_2_fasta  - 
![Screen Shot 2020-08-17 at 9 00 22 PM](https://user-images.githubusercontent.com/9638057/90461740-b2723200-e0cc-11ea-9386-338f46aa2b43.png)

Why are the two slightly different?

Thank you!

**Comment by dcouvin** [comment]
Dear @chahatupreti ,
Thank you for your message.
Indeed, the two files are slightly different because the file contained in the Alignments repository is the result of an alignment (using Muscle software). The alignments were perform in order to get information on conservation metrics (such as overall percentage identity ...).
Best regards,
@dcouvin

**Comment by chahatupreti** [comment]
Gotcha! So if I am just interested in getting the DR sequences, then I should focus on the Drs_X instead of Drs_X_fasta, right?

**Comment by dcouvin** [comment]
Yes that's right!

**Comment by chahatupreti** [comment]
Thank you!
