### ISSUE TITLE
A question when doing test 

### ISSUE THREAD

**Issue by JNdurubing** [dcouvin/CRISPRCasFinder#25]
Can't locate Data/Dumper.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at CRISPRCasFinder.pl line 23.
BEGIN failed--compilation aborted at CRISPRCasFinder.pl line 23.

**Comment by dcouvin** [comment]
Dear @JNdurubing , thank you for your message. Please provide more information. Which operating system do you use? Do you use conda in the same time ? If it is the case, conda should be deactivate to run the tool. Otherwise, you can use the new Singularity container available at : https://crisprcas.i2bc.paris-saclay.fr/Home/Download .
You can also try the following command for Ubuntu : sudo cpanm Data::Dumper
Best,
david
