### ISSUE TITLE
Flank sequence near contig edge has negative coordinate

### ISSUE THREAD

**Issue by tgurbich** [dcouvin/CRISPRCasFinder#43]
Hello! Thank you for this great tool. I am using CRISPRCasFinder v.4.3.2 and I noticed that flank sequence coordinates are reported without taking into account how close to the edge of the contig they are. One of my CRISPR hits begins at position 23, and the left flank sequence is reported to start at position -77 (making an invalid GFF) and its sequence is reported as "unknown". Would it be possible to shorten reported flank sequences in future releases if they are near the edge? 
Thank you!

**Comment by dcouvin** [comment]
Hi @tgurbich,
Thank you for your message. We will try to solve this issue in future releases.
Otherwise, you can also use the "-flank" or "-fl" option to choose the size of the flanking sequence.
Example command: "perl CRISPRCasFinder.pl -in install_test/sequence.fasta -fl 10 -out RES_OUTPUT".
I hope this will help you while waiting for the next version!
All the best,
David
